/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import java.awt.KeyboardFocusManager;
import java.util.Date;
import Modelo.Tarea;
import com.toedter.calendar.JDateChooser;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.Timer;
import java.awt.event.*;
/**
 *
 * @author alvpi y Pascual
 */
public class Vista extends javax.swing.JFrame {
    
    public Controlador controlador;

    /** Creates new form Vista */
    public Vista() {
        initComponents();
        
        jPanel13.setVisible(false);
        //Permite volver al menu inicial
        Volver.setLabel("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        }); 
        //Permite desplazase por los campos con solo el tab
        jTextArea1.setFocusTraversalKeys(
        KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS,
        KeyboardFocusManager.getCurrentKeyboardFocusManager()
            .getDefaultFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS)
        );
        //Permite desplazarse por los campos hacía atras con shift+tab
        jTextArea1.setFocusTraversalKeys(
        KeyboardFocusManager.BACKWARD_TRAVERSAL_KEYS,
        KeyboardFocusManager.getCurrentKeyboardFocusManager()
            .getDefaultFocusTraversalKeys(KeyboardFocusManager.BACKWARD_TRAVERSAL_KEYS)
        );
        //Habilita que cuando pulsemos enter en guardar
        getRootPane().setDefaultButton(jButton1);
        //Formato de la fecha
        jDateChooser1.setDateFormatString("dd/MM/yyyy");
        // Establece la fecha actual como valor por defecto
        jDateChooser1.setDate(new Date()); 
        //Solo permitira selecciona una tarea a la vez
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        //Para que porcentaje vaya de uno en uno 
        //Vamos a settear el porcentaje para que solo se puedan meter porcentajes entre el 1 y el 99 y con un valor por defecto 1
        javax.swing.SpinnerNumberModel modeloPorcentaje = new javax.swing.SpinnerNumberModel(1,1,99,1);
        jSpinner1.setModel(modeloPorcentaje);
        //Tamanno por defecto 
        setSize(860,650);
        //Para que aparezca en el centro de la pantalla
        setLocationRelativeTo(null);
        //Boton de volver
        Volver.setLabel("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });


        

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        label1 = new java.awt.Label();
        NombreListaTaras = new java.awt.TextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel8 = new javax.swing.JPanel();
        Volver = new java.awt.Button();
        jButton1 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel13 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(400, 300));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(744, 444));
        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new java.awt.GridLayout(5, 0));

        jLabel1.setText("Nombre de la tarea");

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField1.setAutoscrolls(false);
        jTextField1.setMinimumSize(new java.awt.Dimension(200, 80));
        jTextField1.setPreferredSize(new java.awt.Dimension(200, 24));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        label1.setText("Nombre de la lista"
        );

        NombreListaTaras.setText(""
        );
        NombreListaTaras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreListaTarasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NombreListaTaras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NombreListaTaras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        jPanel2.add(jPanel4);

        jLabel2.setText("Descripcion");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel5.add(jLabel2);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel5.add(jScrollPane1);

        jPanel2.add(jPanel5);

        jLabel4.setText("Porcentaje");

        jSpinner1.setMaximumSize(new java.awt.Dimension(32767666, 32767666));

        jLabel11.setText("Fecha");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel4)
                .addGap(5, 5, 5)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel11)
                .addGap(5, 5, 5)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel4))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel11))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(jPanel6);

        jLabel5.setText("Prioridad");
        jPanel7.add(jLabel5);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baja", "Media", "Alta" }));
        jComboBox1.setToolTipText("");
        jPanel7.add(jComboBox1);

        jCheckBox1.setText("Completado");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel7.add(jCheckBox1);

        jPanel2.add(jPanel7);

        Volver.setLabel("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        jPanel8.add(Volver);

        jButton1.setText("Guardar");
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton1);

        jPanel2.add(jPanel8);

        jPanel1.add(jPanel2);

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel10.setLayout(new java.awt.GridLayout(2, 0, 5, 0));

        jScrollPane3.setPreferredSize(new java.awt.Dimension(250, 200));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setMaximumSize(new java.awt.Dimension(2000, 200));
        jList1.setPreferredSize(new java.awt.Dimension(250, 100));
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(jList1);

        jPanel9.add(jScrollPane3);

        jPanel10.add(jPanel9);

        jPanel13.setPreferredSize(new java.awt.Dimension(675, 300));
        jPanel13.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jPanel3.setLayout(new java.awt.GridLayout(5, 0, 10, 0));

        jLabel6.setText("jLabel6");
        jPanel3.add(jLabel6);

        jLabel7.setText("jLabel7");
        jPanel3.add(jLabel7);

        jLabel8.setText("Fecha ");
        jPanel3.add(jLabel8);

        jPanel12.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        jLabel9.setText("Prioridad    ");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel12.add(jLabel9);

        jLabel10.setText("jLabel10");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel12.add(jLabel10);

        jPanel3.add(jPanel12);

        jButton2.setText("Editar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton2);

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton3);

        jPanel3.add(jPanel11);

        jPanel13.add(jPanel3);

        jPanel10.add(jPanel13);

        jPanel1.add(jPanel10);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        controlador.addTarea();
    }//GEN-LAST:event_jButton1ActionPerformed
    public void mostrarDescripiconTarea(){
        jPanel13.setVisible(true);
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String tareaSeleccionada = getTareaActiva(); // obtienes la tarea activa
        if (tareaSeleccionada != null) {
            controlador.deleteTarea(tareaSeleccionada);
        } else {
            mostrarToast("⚠ Selecciona una tarea para eliminar");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        String tareaSeleccionada = getTareaActiva(); 
        if (tareaSeleccionada != null) {
            controlador.viewTarea(tareaSeleccionada);
        }
    }//GEN-LAST:event_jList1ValueChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String tareaSeleccionada = getTareaActiva(); // obtienes la tarea activa
        if (tareaSeleccionada != null) {
            controlador.prepararEdicion(tareaSeleccionada);
        } else {
            mostrarToast("⚠ Selecciona una tarea primero");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed

        this.dispose(); // Cierra la vista actual
        new MenuInicial().setVisible(true); // Abre el menú principal 
    }//GEN-LAST:event_VolverActionPerformed

    private void NombreListaTarasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreListaTarasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreListaTarasActionPerformed
    public String getTareaActiva() {
        return jList1.getSelectedValue();
    }
    
    public String getNombreTarea() {
        return jTextField1.getText();
    }
    public String getDescripcionTarea() {
        return jTextArea1.getText();
    }
    public String getPorcentaje() {
        int valorIntroducido = (Integer) jSpinner1.getValue();
        if (valorIntroducido < 1) return "1";
        if (valorIntroducido > 99) return "99";
        return jSpinner1.getValue().toString();
    }
    public String getPrioridad() {
        return jComboBox1.getSelectedItem().toString();
    }
    public Boolean getCompletado() {
        return jCheckBox1.isSelected();
    }
    
    public void setTareas(String[] tareas) {
        jList1.setListData(tareas);
        
    }
    
    public void setNombre(String tmp) {
        jLabel6.setText(tmp);
    }
    public void setPrio(String tmp) {
        jLabel10.setText(tmp);
    }
    public void setDes(String tmp) {
        jLabel7.setText(tmp);
    }
    public void clear() {
    jTextField1.setText("");         // Nombre
    jTextArea1.setText("");          // Descripción
    jSpinner1.setValue(0);           // Porcentaje (asumiendo int o similar)
    jComboBox1.setSelectedIndex(0);  // Prioridad (Baja por defecto)
    jCheckBox1.setSelected(false);   // Completado
    NombreListaTaras.setText("");    // Ponemos el campo de nombreListaTareas en blanco de nuevo
    
    }
    public void setNombreEdicion(String nombre) {
    jTextField1.setText(nombre);
    }
    public void setDescripcionEdicion(String des) {
        jTextArea1.setText(des);
    }
    public void setPrioridadEdicion(String prio) {
        jComboBox1.setSelectedItem(prio);
    }
    public void setPorcentajeEdicion(String porcentaje) {
        jSpinner1.setValue(Integer.parseInt(porcentaje));
    }
    public void setCompletadoEdicion(boolean completo) {
        jCheckBox1.setSelected(completo);
    }
    //Tema fecha
    public Date getFechaTarea() {
        return jDateChooser1.getDate();
    }
    public void setFechaEdicion(Date fecha) {
       jDateChooser1.setDate(fecha);
    }
    public void mostrarToast(String mensaje) {
        JDialog dialog = new JDialog();
        //maquetación del popup
        dialog.setUndecorated(true);
        dialog.setAlwaysOnTop(true);
        dialog.setLayout(new java.awt.BorderLayout());
        dialog.add(new javax.swing.JLabel(mensaje, javax.swing.SwingConstants.CENTER), java.awt.BorderLayout.CENTER);
        dialog.setSize(300, 80);
        //Permite centrar
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
        //Cerramos el popup en ms 
        new javax.swing.Timer(350, e -> dialog.dispose()).start();
    }  
    public String getNombreListaActual() {
        String nombre = NombreListaTaras.getText().trim();
        return nombre.isEmpty() ? "IPC" : nombre;
    }
    public void mostrarTarea(Tarea tarea) {
    if (tarea != null) {
        jLabel6.setText(tarea.getNombre());
        jLabel7.setText(tarea.getDescripcion());
        jLabel8.setText("Fecha: " + tarea.getFecha().toString());
        jLabel10.setText(tarea.getPrioridad());
        jPanel13.setVisible(true); // muestra el panel con la descripción de la tarea
    } else {
        mostrarToast("⚠ Tarea no válida");
    }
}
    public void prepararEdicion(Tarea tarea) {
        if (tarea != null) {
            jTextField1.setText(tarea.getNombre());
            jTextArea1.setText(tarea.getDescripcion());
            jSpinner1.setValue(Integer.parseInt(tarea.getPorcentajeCompletado()));
            jComboBox1.setSelectedItem(tarea.getPrioridad());
            jCheckBox1.setSelected(tarea.getEstadoTarea());
            jDateChooser1.setDate(tarea.getFecha());
        } else {
            mostrarToast("⚠ No se puede editar, tarea inválida");
        }
    }
    public void setControlador(Controlador controlador){
           this.controlador = controlador;
           controlador.setTareas();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField NombreListaTaras;
    private java.awt.Button Volver;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables

}
